### PR TITLE
snapshot restore error display

### LINKED ISSUE #102: snapshot / restore error display
In case of snapshot (or restore snapshot) fails a comprehensive error should be shown to user

### PR DESCRIPTION
**Pull request by shamis**
Depends on PR https://github.com/K2InformaticsGmbH/imem/pull/81
Fixes #102 
image

### CODE REVIEW

File: src/imem_adapter.erl [hunk 1]
```diff
@@ -820,10 +820,15 @@ send_result_table_cmd(From, BinCmd, Results) ->
         [invalid_connection | _Rest] ->
             From ! {reply, error_invalid_conn()};
         _ ->
-            ListNames = [binary_to_list(X) || X <- TableErrors],
-            BinTblError = list_to_binary(string:join(ListNames, ",")),
+            TableErrorsBin = lists:foldl(
+                fun({Table, Error}, Acc) ->
+                        ErrorBin = imem_datatype:term_to_io(Error),
+                        <<Acc/binary, Table/binary, <<" - ">>/binary, ErrorBin/binary, <<", ">>/binary>>;
```
Comment (c-bik) [inline src/imem_adapter.erl]: No need qualify constant strings. Try: `<<Acc/binary, Table/binary, " - ", ErrorBin/binary, ", ">>`

File: src/imem_adapter.erl [hunk 2]
```diff
@@ -820,10 +820,15 @@ send_result_table_cmd(From, BinCmd, Results) ->
...
+                   (Table, Acc) ->  <<Acc/binary, Table/binary, <<", ">>/binary>>
```
Comment (c-bik) [inline src/imem_adapter.erl]: Same https://github.com/K2InformaticsGmbH/dderl/pull/232/files#r67305627

File: src/imem_adapter.erl [hunk 3]
```diff
@@ -820,10 +820,15 @@ send_result_table_cmd(From, BinCmd, Results) ->
...
+                end, <<>>, TableErrors),
+            FTableErrorsBin = re:replace(TableErrorsBin, <<", $">>, <<>>, [{return, binary}]),
```
Comment (c-bik) [inline src/imem_adapter.erl]: Use string constants (in stead of binary)
