### PR TITLE
remote_apps - using application:which_applications()

### LINKED ISSUE #531: oci connection - remote_apps results in error
image

```erlang
2018-06-12 15:10:42.683 [error] <0.24408.128>@dderl_session:spawn_process_call:636 [_DDRL_] {dderl_session,636} Problem processing command: error:undef
[{<<"remote_apps">>,[{<<"connection">>,<<"g2gDZAAIb2NpX3BvcnRnZAAhc2JzZ3VpQFpISEFQTU9QLVNCU00wMS5pdC5id25zLmNoAAA0XgAAAIACYgBIiqA=">>}]}]
[{oci_port,run_cmd,[which_applications,[],{oci_port,<0.13406.128>,4754080}],[]},{oci_adapter,process_cmd,6,[{file,"d:/Projects/Git/sbsgui/_build/default/lib/dderl/src/oci_adapter.erl"},{line,211}]},{dderl_session,spawn_process_call,8,[{file,"d:/Projects/Git/sbsgui/_build/default/lib/dderl/src/dderl_session.erl"},{line,633}]}]
```

clicking on `show remote` in the About dialog results in error on a oracle connection.

### PR DESCRIPTION
**Pull request by shamis**
fixes #531 
erloci will always be running local to dderl server

### CODE REVIEW

File: src/oci_adapter.erl [hunk 1]
```diff
@@ -208,7 +208,7 @@ process_cmd({[<<"remote_apps">>], ReqBody}, _Sess, _UserId, From, #priv{connecti
     Connection = ?D2T(proplists:get_value(<<"connection">>, BodyJson, <<>>)),
     case lists:member(Connection, Connections) of
         true ->
-            Apps = Connection:run_cmd(which_applications, []),
+            Apps = application:which_applications(),
```
Comment (c-bik) [inline src/oci_adapter.erl]: Add comment above
```erlang
% erloci instance is always in local node
```
