### PR TITLE
Logging in after screensaver - erlimem session timeout

### LINKED ISSUE #320: Logging in after screensaver - erlimem session timeout
To reproduce
- wait for the screensaver to be active
- click on Login
- wait till erlimem session is timedout (authorization timeout)
- trying to login fails.

Screensaver does not come up after login from screensaver unless a user action is made

### PR DESCRIPTION
**Pull request by shamis**
Fixes  #320

### CODE REVIEW

File: priv/static/scripts/login.js [hunk 1]
```diff
@@ -125,17 +125,14 @@ function loginCb(resp) {
...
-        }
+        removeScreenSaver();
     } else if (resp.hasOwnProperty('changePass')) {
         change_login_password(resp.changePass, true);
-    } else {
+    } else if (resp == 'logout') {
+        removeScreenSaver();
+        logout(true);
+    }
+      else {
```
Comment (acautin) [inline priv/static/scripts/login.js]: why this is in a different line ?

File: priv/static/scripts/login.js [hunk 2]
```diff
@@ -261,8 +269,8 @@ function inputEnter(layout) {
     loginAjax(data);
 }
 
-export function logout() {
-    if(dderlState.connection) {
+export function logout(isForceufl) {
```
Comment (acautin) [inline priv/static/scripts/login.js]: what is ufl?

**Comment by shamis** [comment]
@acautin have made the changes. Please verify
