### PR TITLE
Saml authentication failiure fix

### LINKED ISSUE #430: SAML authentication fails in 1.5.0
Access log implementation was not done on saml_handler

> Ranch listener https terminated in dderl_saml_handler:info/3 with reason: no function clause matching dderl_saml_handler:info({access,#{cmd => [<<"login">>],logLevel => 2}}, {http_req,{sslsocket,{gen_tcp,#Port<0.20027>,tls_connection,<0.958.0>},<0.14064.13>},ranch_ssl,keepalive,...}, {state,{esaml_sp,{esaml_org,[],[],[]},{esaml_contact,[],[]},{'RSAPrivateKey','two-prime',20866187756181838283406930997587379754272275552878749781563838759268199345989222618015623374823172492767018583878915071360377282967330354266996374241625429938339133305458442596919491105449134215771300748927386671072942762793167615323031532156361288462026657358684177611998839443796464992799794694160057284958180096021580941883151984441252762776788592414606623715072396311327516151464183519169154489798443805132304434149192242728719552036458842587005436318642119102319079728441045210516844996459449542329174420404582884774279422003164625089464457414444618047434736771165793823610838380361421125636194350819355298749241,...},...},...}) line 33

### PR DESCRIPTION
**Pull request by shamis**
fixes #430

### CODE REVIEW

**Comment by shamis** [comment]
@c-bik  have made the suggested changes please verify

File: src/dderl_saml_handler.erl [hunk 1]
```diff
@@ -7,16 +7,18 @@
 
 -export([fwdUrl/3]).
 
--record(state, {sp, idp}).
+-record(state, {sp, idp, terminateFun}).
```
Comment (c-bik) [inline src/dderl_saml_handler.erl]: * rename . `terminateFun` -> `terminateCallback`

File: src/dderl_saml_handler.erl [hunk 2]
```diff
@@ -41,9 +43,15 @@ info({reply, {saml, UrlSuffix}}, Req, State) ->
...
-    {ok, Req1, State}.
+    {ok, Req1, State};
+info({access, Log}, Req, State) ->
+    {OldLog, Req} = cowboy_req:meta(accessLog, Req, #{}),
+    {loop, cowboy_req:set_meta(accessLog, maps:merge(OldLog, Log), Req), State, hibernate};
+info({terminateFun, {Mod, Fun}}, Req, State) ->
+    {loop, Req, State#state{terminateFun = {Mod, Fun}}, hibernate}.
 
-terminate(_Reason, _Req, _State) -> ok.
+terminate(Reason, Req, #state{terminateFun = {Mod, Fun}} = State) ->
```
Comment (c-bik) [inline src/dderl_saml_handler.erl]:
```erlang
terminate(Reason, Req, #state{terminateCallback = Fun} = State) when is_function(Fun, 3) ->
    Fun(Reason, Req, State).
```
